### ISSUE TITLE
Functions tracker

### ISSUE THREAD

**Issue by musm** [musm/Amal.jl#1]
A couple are in the pipeline

# Trig functions
- [ ] acos
- [ ] asin
- [ ] atan
- [ ] atan2
- [ ] sin
- [ ] cos
- [ ] tan

# Hyperbolic functions
- [ ] acosh
- [ ] asinh
- [ ] atanh
- [ ] cosh
- [ ] sinh
- [ ] tanh
# Exponential and logarithmic
- [x] exp
- [x] exp2
- [x] exp10
- [ ] expm1
- [x] log
- [ ] log10
- [ ] log1p
- [ ] log2
- [ ] logb

# Misc
- [ ] pow
- [x] frexp
- [x] ilog2 
- [x] ldexp
- [ ] cbrt

**Comment by RoyiAvital** [comment]
Why have you dropped this project?

**Comment by oxinabox** [comment]
I would guess because it has largely all been superceded with Julia having implementions of all the libm now done in Julia itself in the Base stdlib.

**Comment by RoyiAvital** [comment]
I thought this package aims for SLEEF or better performance, is that the current state?

**Comment by musm** [comment]
Dropped because: (1) @oxinabox  is correct and (2) there is the other package SLEEF.jl which is fully fledged and has all the method with their own vectorized optimized implementations

**Comment by RoyiAvital** [comment]
@musm , I see. I thought this package was to overcome SLEEF's pitfalls. This is at least what I saw on another discussion.
